# Generated by Django 5.2.7 on 2025-10-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_variations'),
        ('orders', '0002_remove_orderproduct_variations'),
        ('store', '0002_productgallery_reviewrating_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
